### ISSUE TITLE
Missing file, It doesn't work.

### ISSUE THREAD

**Issue by MrLoading** [7fantasysz/MSCRED#1]
problem:
I spend a few days and I run this but it doesn't work. And it seems that the necessary files are missing. Documents and instructions are needed .
environment:
```
windows 10 X64
python 3.6
tensorflow 1.12.0
```
maybe help:
```python "C:/******/MSCRED-master/code/matrix_generator.py"
Namespace(gap_time=10, max_time=20000, min_time=0, raw_data_path='../data/synthetic_data_with_anomaly-s-1.csv', save_data_path='../data/', step_max=5, test_end_point=20000, test_start_point=8000, train_end_point=8000, train_start_point=0, ts_type='node', win_size=[10, 30, 60])
generating signature with window 10...
generating signature with window 30...
generating signature with window 60...
matrix generation finish!
Traceback (most recent call last):
generating train/test data samples...
  File "C:/******/MSCRED-master/code/matrix_generator.py", line 283, in <module>
    generate_train_test_data()
  File "C:/******/MSCRED-master/code/matrix_generator.py", line 245, in generate_train_test_data
    data_all.append(np.load(path_temp))
  File "E:\******\lib\site-packages\numpy\lib\npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhaos/ts_data_csv2/signature_matrix/matrix_win_10total_count.npy'

Process finished with exit code 1
```
How can I run this project on Windows?
Please help me.

**Comment by xuesongwang** [comment]
Hi,
 I think this is due to the update of the author's code and some of the files are renamed. You need to understand the code structure and tried to generate data using matrix_generator.py . Also, you need to change the output of this file, e.g., matrix_win_10.npy to substitute the directory in the MSCRED_TF.py

**Comment by 7fantasysz** [comment]
@xuesongwang Thanks for your comments and you are right. 
@MrLoading The path is just for my testing purpose and it is Linux style of path, instead of windows. You need to manage your path correspondingly.

**Comment by phdYang** [comment]
> matrix_win_10.np

I want to ask about how to build data_all in the generate_train_test_data () method in matrix_generator.py, I guess he is missing at least 9 files

**Comment by xuesongwang** [comment]
@phdYang  Yes, you are right, but I think you can process your own data with this matrix generator and then validate the proposed method.
